### ISSUE TITLE
PR previews have undesired side effect for main page (deleted html pages are persisting)

### ISSUE THREAD

**Issue by jbusecke** [ProjectPythia/cookbook-actions#120] opened 2024-09-16 16:55 UTC
I am tracking an issue with our docs over at LEAP [here](https://github.com/leap-stc/leap-stc.github.io/issues/179). We just noticed that the deployment branch retains html files which are not currently part of the book anymore! 

I figure this is due to the setting [here](https://github.com/ProjectPythia/cookbook-actions/blob/419348af440fabff6e969432e18ef5a64a76bffb/.github/workflows/deploy-book.yaml#L71) which I think is necessary for the preview to work. 

I think the desired solution here would be to specify a directory (`/preview`) that is retained, while all other files represent a current commit? It seems that this has been brought up as feature request upstream (https://github.com/peaceiris/actions-gh-pages/issues/718 and https://github.com/peaceiris/actions-gh-pages/issues/771) but is not currently implemented. 

Wondering what folks here think about this? This seems like a pretty bad behavior to me (and has caused some major confusion with our users), so I would be willing to implement a custom solution until an upstream solution is available. But I think such a solution should definitely live here?

**Comment by jbusecke** [comment] 2024-09-16 16:59
I just saw [this](https://github.com/peaceiris/actions-gh-pages/issues/718#issuecomment-1221375330) which might be a possible solution!

**Comment by brian-rose** [comment] 2024-09-23 19:51
Thanks for bringing this up, @jbusecke! I completely agree that this is bug in the current implementation.

The potential switch to https://github.com/JamesIves/github-pages-deploy-action instead of https://github.com/peaceiris/actions-gh-pages that you referred to above looks promising to me. Both actions have similar functionality and both seem to be in wide use, but https://github.com/JamesIves/github-pages-deploy-action looks to be under more active current development.

@erogluorhan I think it makes sense for the Pythia infrastructure team to take a look at this.

**Comment by erogluorhan** [comment] 2024-09-25 14:22
Thanks @jbusecke ! @brian-rose, I also agree that we need to look into this. Hey @ProjectPythia/infrastructure , anyone available to look into this till the next iteration?

**Comment by jukent** [comment] 2024-10-10 19:49
@jbusecke to test whether my fix in #125 works, could you temporarily run your workflow with the small change as in https://github.com/jukent/cookbook-template/pull/14/files

I am able to verify that the new action runs successfully, but do not know what files to look for to make sure they are no longer persisting.

**Comment by erogluorhan** [comment] 2024-10-17 16:39
@jbusecke and @jukent just an FYI, I've merged PR #125 that led this one to get closed, but depending on @jbusecke future observations, we can re-open

**Comment by jbusecke** [comment] 2024-10-17 18:06
Just running the deploy action from main:
```
  deploy:
    needs: build
    uses: ProjectPythia/cookbook-actions/.github/workflows/deploy-book.yaml@main
    with:
      publish_dir: "book/_build/html"
```
[here](https://github.com/leap-stc/leap-stc.github.io/blob/main/.github/workflows/publish-book.yaml) (with no changes in our repo) I am getting an error:

```
fatal: not in a git directory
```
https://github.com/leap-stc/leap-stc.github.io/actions/runs/11390409843/job/31692035052#step:5:43

I am not quite sure what is happening here yet, but it seems that #125 has broken backwards compatibility somehow?

**Comment by jbusecke** [comment] 2024-10-17 18:11
The only difference I see with @jukent s [setup](https://github.com/jukent/cookbook-template/actions/runs/11277342488/workflow) is that I define a custom `publish_dir`.

**Comment by jbusecke** [comment] 2024-10-17 18:34
Have to step away from this for a bit, but will hopefully follow up in a bit as this is currently breaking our build (I can easily revert back to a previous version though).

**Comment by jbusecke** [comment] 2024-10-18 13:48
I have an open PR #129 which fixes the issues on our end, but there are some arguments that I do not quite know what to do with. Feedback much appreciated.

**Comment by brian-rose** [comment] 2024-10-25 21:05
@jbusecke I spent time on this today. After some back and forth (#129, #131, #134) I think things are working as intended now.

Please report back here when you get a chance about any outstanding issues.

**Comment by jbusecke** [comment] 2024-10-28 14:56
@brian-rose thanks a lot. Ill quickly build our docs from main here and will report back. Can we also release a version after that?

**Comment by jbusecke** [comment] 2024-10-28 15:11
I am getting the following warning in the `Run CumulusDS/get-yaml-paths-action@v1.0.2` step: 
```
Warning: Unexpected input(s) 'execute_notebooks', 'binderhub_url', 'timeout', valid inputs are ['file']
```
and also:

```
The following actions use a deprecated Node.js version and will be forced to run on node20: CumulusDS/get-yaml-paths-action@v1.0.2. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```
@brian-rose should I open a separate issue for this?

but generally our [production deployment](https://github.com/leap-stc/leap-stc.github.io/actions/runs/11556651635/job/32164913020) seems to work. 

I also tested our preview [here](https://github.com/leap-stc/leap-stc.github.io/pull/192) and it seems to be fine (or are there other side effects I should be checking for?

**Comment by brian-rose** [comment] 2024-10-28 16:31
> I also tested our preview [here](https://github.com/leap-stc/leap-stc.github.io/pull/192) and it seems to be fine (or are there other side effects I should be checking for?

Great! I'm just wondering if we're ready to close this issue. I *think* the original problem of persistent html pages has been solved, but I haven't 100% verified this myself.

**Comment by jbusecke** [comment] 2024-10-28 18:09
Oh shoot, I just realized I am still running from my PR branch! https://github.com/leap-stc/leap-stc.github.io/blob/main/.github/workflows/publish-book.yaml

Ill retest just to make sure. After that I think this is ok to close.

**Comment by jbusecke** [comment] 2024-10-28 18:25
Testing now using the most recent main branch.

- [ ] [Production run](https://github.com/leap-stc/leap-stc.github.io/actions/runs/11560249285)
- [ ] [Preview Test](https://github.com/leap-stc/leap-stc.github.io/pull/194)

**Closed** 2024-10-28 18:27 UTC
Labels: bug
